spring:
  profiles:
    active: "boot,local"
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: "SPOTIFY_APP_ID"
            client-secret: "YOUR_SECRET_VALUE"
            client-name: "Spotify client"
            scope:
              - "user-read-private"
              - "user-read-email"
              - "user-library-read"
              - "user-library-modify"
              - "playlist-modify-public"
              - "playlist-modify-private"
            redirect-uri: "http://localhost:8080/login/oauth2/code/spotify"
            client-authentication-method: "basic"
            authorization-grant-type: "authorization_code"
        provider:
          spotify:
            authorization-uri: "https://accounts.spotify.com/authorize"
            token-uri: "https://accounts.spotify.com/api/token"
            user-info-authentication-method: header
            user-info-uri: "https://api.spotify.com/v1/me"
            user-name-attribute: "id"

spotify:
  client:
    cache:
      maxSize: 2048
      ttl: 300


logging.level.io.github.gnupinguin.spotify.client: DEBUG
